name: Sync Notion to GitHub

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # 매일 자정 (UTC)에 실행

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Sync Notion to Markdown
        uses: tryfabric/notion-github-action@v1
        with:
          notion-token: ${{ secrets.NOTION_TOKEN }}
          notion-db: '221efa77dcdf801a8b1fd64ac2bc0df8'
          # output-dir: 'content' # 필요한 경우 주석 해제

      - name: Commit and push changes
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          # 변경사항이 있을 때만 커밋하고 푸시하도록 수정
          git diff-index --quiet HEAD || (git commit -m "Auto-sync Notion content" && git push)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
