name: Sync Notion to GitHub

on:
  workflow_dispatch: # 수동 실행 가능
  schedule:
    - cron: '0 0 * * *' # 매일 자정 (UTC)에 실행

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Sync Notion to Markdown
        uses: tryfabric/notion-github-action@v1 # 현재 사용 중인 액션
        with:
          # --- 수정된 부분 ---
          notion-token: ${{ secrets.NOTION_TOKEN }}
          notion-db: '221efa77dcdf801a8b1fd64ac2bc0df8'
          # -------------------------------


      - name: Commit and push changes
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Auto-sync Notion content" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
